# This tells Railway's build system what to do

[phases.setup]
cmds = ["bash build.sh"]

[start]
# This is the command to start your web server
# It replaces the need for a Procfile
cmd = "gunicorn backend.main:app"